### PR TITLE
Header mobile style

### PR DESCRIPTION
**Pull request by Nishune**
### My PR for the Header navigation styling.

This PR contains both SCSS and also necessary updates in JS to make the styling work as intended. Also i fixed some alt-text in the JSON file since this was not correct before. Lastly i fixed an error for the kids.html navigation, which should now work as intended.

### Quick checkbox for the tester:

- [x] The menu is now styled similar to the figma design.
- [x] When clicking on the hamburger menu, an overlay opens.
- [x] There is a bigger logotype in the overlay.
- [x] The styling is similar for the link in the overlay.
- [x] You can close the overlay by pressing the X-button, or by clicking on the blurry overlay.
- [x] The navigation between index.html, kids.html, about.html now work as intended.

### Image preview on navigation bar:

image

### Image preview of the overlay when clicking hamburger button:

image

### CODE REVIEW

**Comment by viktornoskire** [comment]
## Comment
Very good work and the functionality is working as intended. No problems at all there. One thing I noticed while testing different mobile devices the menu goes off screen as shown below. I don't know exactly how to fix this problem but I'm sure that you are going to be able to fix it in no time.

### On iPhone SE
image
### On Samsung Galaxy S8+
image

**Comment by Nishune** [comment]
> ## Comment
> Very good work and the functionality is working as intended. No problems at all there. One thing I noticed while testing different mobile devices the menu goes off screen as shown below. I don't know exactly how to fix this problem but I'm sure that you are going to be able to fix it in no time.
> 
> ### On iPhone SE
> image
> 
> ### On Samsung Galaxy S8+
> image

**Comment by Nishune** [comment]
@viktornoskire 

I have fixed that problem now, i have added overflow-y to the overlay. Also fixed the height property to better fit screen sizes, and adjusted its position to always be centered on the screen. It should work as intended now.

### image preview on Iphone SE:

image


### Image preview om samsung S8:

image

**Review by viktornoskire — APPROVED** [review]
Very good fix! Now it works as intended and the menu doesn't overflow and dissapear. Ready to be merged!

**Pull request merged**
